# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Tanushree Naik
# Description of the Site
description: Research and Data Analyst
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Homepage,Data, Analyst
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /assets/images/SP_Skyline_668.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: contact@tanushreenaik.com
facebook_username: 
twitter_username: tanushree_naik
instagram_username:
linkedin_username:
github_username: TanushreeNaik
youtube_channel_id:
reddit_username:
behance_username:
dribbble_username:
spotify_username:

# Google Analytics
google-analytics:

# Disqus
disqus-shortname:

# Name of the Author
author-name: Tanushree Naik
# URL for the Image of the Author
author-image: https://lh5.googleusercontent.com/_6OfFfBbXSONJHAfMT1bEl-d_oCqSzq4BHChdLSn3UrTMThu1iAqfge7jwBX48j208_2L5tQSw=w1280
# 60 Words About the Author
author-about: I'm an enthusiastic Data Scientist excited to work on augmentation of health sciences using big data and machine learning. I like working in a team and interacting with people. Being able to identify problems/questions and finding solutions to them is what excites me! I am self-motivated and have the proven ability to meet milestones and deliver results in a time bound manner that have led to the completion of 2 projects and 3 international publications.  I possess strong communication skills as evidenced by 2 poster presentations, and 5 talks on national and international platforms during my PhD. In the field of Biology, I have worked on several different model systems giving me the ability to learn and adapt quickly. I am currently looking for opportunities in the filed of data science and eager to work in an energetic team.


# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/TanushreeNaik

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - local/
